{% set name = "ezca" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35b7dc15b08abb829712b7f40a35a4ab4ceba497cd21229ea9b644d9cdef5d13

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - setuptools-scm
  run:
    - pcaspy
    - python >=3.5
    - pyepics >=3.4.1    

test:
  requires:
    - pip
    - pytest
  imports:
    - ezca
  commands:
    - pip check
    - python -m pytest --pyargs ezca

about:
  home: https://git.ligo.org/cds/software/python-ezca/
  dev_url: https://git.ligo.org/cds/software/python-ezca/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING-GPL-3
  summary: aLIGO CDS Python EPICS interface
  description: |
    Ezca is a wrapping around pyepics containing methods specially
    designed for interfacing with the Advanced LIGO CDS front-end control
    system (e.g. "RCG").  Beyond providing standard methods for reading
    and writing EPICS channels, it also includes the LIGOFilter object for
    interacting with CDS Standard Filter Modules.  It also handles
    abstracting information about the interferometer under control, and
    sub-classing specific control domains.
    It is specifically designed to be integrated into the Guardian
    automation platform, but it's also perfectly usable on it's own.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
    - evonreis
