{% set name = "ezca" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/53/06/0d30f566d5967701211c33eaab50112fb506398613b17bb28f8f09efaf2f/ezca-1.5.0.tar.gz
  # url: https://git.ligo.org/cds/python-ezca/-/archive/{{ version }}/python-ezca-{{ version }}.tar.gz
  #sha256: 1afbe01d6d25bf04493b14d9538dea278de0b1ebd0eac78104fb867edc8914e5
  sha256: 35b7dc15b08abb829712b7f40a35a4ab4ceba497cd21229ea9b644d9cdef5d13

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
    - setuptools-scm
  run:
    - pcaspy
    - python >=3.5
    - pyepics >=3.4.1    

test:
  requires:
    - pip
  commands:
    # check requirements
    - python -m pip check
    # run test suite
    - python -m unittest discover ezca.test_ezca

about:
  home: https://git.ligo.org/cds/python-ezca/
  dev_url: https://git.ligo.org/cds/python-ezca/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: aLIGO CDS Python EPICS interface
  description: |
    Ezca is a wrapping around pyepics containing methods specially
    designed for interfacing with the Advanced LIGO CDS front-end control
    system (e.g. "RCG").  Beyond providing standard methods for reading
    and writing EPICS channels, it also includes the LIGOFilter object for
    interacting with CDS Standard Filter Modules.  It also handles
    abstracting information about the interferometer under control, and
    sub-classing specific control domains.
    It is specifically designed to be integrated into the Guardian
    automation platform, but it's also perfectly usable on it's own.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - jrollins
