travis:
  secure:
    BINSTAR_TOKEN: erjQmO2YFRz2e5fQmqpKJUga+zWouwvfv1Q+Bro3YwShNWl9pn90LGIPuQ6j4tYlR7q7HX22qvvCRSxCauENpoYaU6pCzNJxxlF8yyhqc7efwlrlGnYSTxEUfXrhclakyHbKDmJBp2gtMSoZdzMKfa6LscjNnV/tvD65zajFgOuLjL4yYHaV8cN3bbgoNInCIL4FvwTcTdqibc07OgAVOk8ry1oL7JQ3wv5xpEK52TUAXqQNcJA/iDI4l3f38w+oMR5US8j6snA2YTYPETJjGAo2YJnyLkqYGCj8uGN+UB61AMLS1L44wEHqSAxuHupe45BpwMLr7v97P/vaEkzI0g60VuzVCH9KaMt9/0NrrwbfDxUdfSgVW+aw17F3GYQXxMg4cV2o0nEFB7SPz7z3bLHHjkXUG0rzrJbkfq6j5L3vz17JXMnTsxy+EzroH0CA58SBaLfadNoNyLhnmagwjAK/JI0paI+Rr/cEklE2xpdfy7pd71Vgc0Bozqg47NKtlaES/ARhMXwt5NXjTM7XVBqMsTs1aYWPu8DUU0hXR85pwLBnci6WhggAILRxfAU/W4k6Yb22QceOQSnISvHoYc/aUhLkYvr5SpCwu5Za+0cYJ6y/UV3hsfS0YBu3Wwq7J+WXnwY30AhZqCO++6q+FGuvJ3VE7A2n6B9ZqVyhx/g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
